### ISSUE TITLE
Project Uses Unsupported Tweet URL Format

### ISSUE THREAD

**Issue by EthanC** [TheLovinator1/discord-twitter-webhooks#71]
Hi there, I've recently migrated from another project - I appreciate the active development!

One issue I've run into is that the Discord and/or Twitter client on Android doesn't support the `/i/web/status/` Tweet URLs that this project uses. When attempting to open these links (via embed author or message content), I'm kicked back to Discord (see video below.) I'm unsure if this issue is present on iOS.

Question is: Can a config variable be added to utilize a working Tweet URL format?

**Examples:**

- Current (Non-Standard?, Does Not Work): https://twitter.com/i/web/status/1637860827133796370
- Proposed (Standard, Works): https://twitter.com/charlieINTEL/status/1637860827133796370
- Alternative (Non-Standard, Works): https://twitter.com/userId/status/1637860827133796370

**Video:**

https://user-images.githubusercontent.com/16727756/226424475-a707e3d9-c4b7-46b7-9dc2-310ada8475f0.mp4

**Comment by TheLovinator1** [comment]
Hi!

Thanks for the issue, I removed the /web/ part from the URL. That seems to work on every device.

Do you want me to add the username to the URL? I can't remember why I went with https://twitter.com/i/ instead of https://twitter.com/charlieINTEL/ but I can probably add it without a problem. ¯\_(ツ)_/¯

A lot of people have asked how to make the URL more visible so I modified the embed so the tweeter name is blue. One disadvantage with that is that the small avatar to the left of the name had to go, but I changed the bot so that it modifies the webhook avatar instead.
Is this better or should I revert the change? (Or make it customizable) 

Should I add @charlieINTEL to the username? Right now it is only the CharlieIntel part

Is there anything else I should add or fix?

**Comment by EthanC** [comment]
Username in the URL would be ideal. `/i/status/` works because both the web and mobile clients will resolve the username regardless of what you replace `i` with, but it looks weird if you share that link with someone since that's not the _normal_ format.

Personally, this would be the most appealing solution to the author and Tweet URL issue you've mentioned:

```py
embed.set_author(f"{displayName} (@{username})", url=f"https://twitter.com/{username}", icon_url=avatarUrl)
embed.set_title("Tweet")
embed.set_url(f"https://twitter.com/{username}/status/{tweetId}")
```
