### ISSUE TITLE
t.co links remain regardless of setting; embedded images are cropped

### ISSUE THREAD

**Issue by dziban303** [TheLovinator1/discord-twitter-webhooks#81]
I've tried the `DISABLE_REMOVE_TCO_LINKS` setting both ways (because it's not super clear which setting does what) but it still provides the t.co link. 

Additionally, is it possible to present the attached image in an uncropped format? Discord does apparently support that, because Tweetshift does it:

![image](https://user-images.githubusercontent.com/7931765/228495780-465d14b0-7c5e-4981-9b1f-953e3dcbdbe8.png)

Cheers

**Comment by EthanC** [comment]
@TheLovinator1 It seems the embed attempts to display a gallery of images when there is only one. Maybe if there is only one image, you should just use `set_image` rather than [sending an array with a single image](https://github.com/TheLovinator1/discord-twitter-webhooks/commit/1a72da5a5693c126da4a550d74d56f0f7a75aed5#diff-43d85680d648061355ccfc1d500f5ce00a08f47ac1d66e80879022ebb33a321cR61)?

![image](https://user-images.githubusercontent.com/16727756/228744864-a876f091-49df-4bf5-8514-bff9377667f9.png)

**Comment by dziban303** [comment]
In my testing the other day, it actually did send the unobfuscated link once. I moved on to try another setting. In my next test tweet, the t.co link was back. Changing the other setting (I forget which) back to the default made no difference, the t.co link has remained no matter what I do.

**Comment by TheLovinator1** [comment]
Hi, sorry for the late fix. Both should be working again.

**Comment by dziban303** [comment]
Yep, they're working! Gonna close
